name: Unzip ZIP File

on:
  push:
    paths:
      - '22213.zip'   # trigger only when this file is changed

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip file
        run: |
          unzip -o 22213.zip -d extracted/
          ls extracted/
